# Generated by Django 2.2.5 on 2019-09-28 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameplay', '0002_auto_20190917_0106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='status',
            field=models.CharField(choices=[('D', 'Draw'), ('L', 'Second Player Wins'), ('S', 'Second Player To Move'), ('W', 'First Player Wins'), ('F', 'First Player To Move')], default='F', max_length=1),
        ),
        migrations.AlterField(
            model_name='move',
            name='by_first_player',
            field=models.BooleanField(editable=False),
        ),
    ]
